name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT: "clash-formal"
  ATTIC_CACHE: "http://${{ secrets.ATTIC_SERVER_IP }}:9200"
  NIX_CONFIG: |
    extra-substituters = $ATTIC_CACHE/$PROJECT
    extra-trusted-public-keys = ${{ secrets.ATTIC_CACHE_PK }}
    netrc-file = /etc/nix/netrc
  NETRC_FILE: |
    machine ${{ secrets.ATTIC_SERVER_IP }}
    password ${{ secrets.ATTIC_PULL_JWT_TOKEN }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  nix-build:
    name: "Cache Nix DevShell"
    runs-on: [self-hosted, compute]
    container:
      image: ghcr.io/qbaylogic/clash-formal-ci:20260326-687dd7d
      options: --memory=30g
    needs: []
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v5
      - name: "Repository specific setup"
        run: |
          deploykey "ghc-typelits-proof-assist" "${{ secrets.DEPLOY_KEY_PROOF_ASSIST_PLUGIN }}" && \
          echo "${{ env.NIX_CONFIG }}" >> /etc/nix/nix.conf && \
          echo "${{ env.NETRC_FILE }}" > /etc/nix/netrc
      - name: "Login to the local cache"
        run: |
          attic login \
            --set-default "${{ env.PROJECT }}" \
            "${{ env.ATTIC_CACHE }}" \
            "${{ secrets.ATTIC_PUSH_JWT_TOKEN }}"
      - name: "Build and cache the Nix devShell"
        run: |
          nix build --no-link .#devShells.x86_64-linux.allFeatures
          attic push \
            "${{ env.PROJECT }}" \
            "$(nix path-info .#devShells.x86_64-linux.allFeatures)"
      - name: "Build and cache clash-crypto untested"
        run: |
          nix build --no-link .#packages.x86_64-linux.hitltHsPkgs.clash-crypto
          attic push \
            "${{ env.PROJECT }}" \
            "$(nix path-info .#packages.x86_64-linux.hitltHsPkgs.clash-crypto)"

  pre-check:
    name: "No Warnings"
    runs-on: [self-hosted, compute]
    timeout-minutes: 20
    container:
      image: ghcr.io/qbaylogic/clash-formal-ci:20260326-687dd7d
      options: --memory=30g
    needs: [ nix-build ]
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v5
      - name: "Repository specific setup"
        run: |
          deploykey "ghc-typelits-proof-assist" "${{ secrets.DEPLOY_KEY_PROOF_ASSIST_PLUGIN }}" && \
          echo "${{ env.NIX_CONFIG }}" >> /etc/nix/nix.conf && \
          echo "${{ env.NETRC_FILE }}" > /etc/nix/netrc
      - name: "Compile"
        run: |
          nix develop --command bash \
            -c "cabal build --enable-tests --ghc-option -Werror"

  Simulation-Tests:
    name: "Sim: ${{ matrix.test.name }}"
    runs-on: [self-hosted, compute]
    timeout-minutes: 60
    container:
      image: ghcr.io/qbaylogic/clash-formal-ci:20260326-687dd7d
      options: --memory=16g
    needs: [ nix-build ]
    strategy:
      matrix:
        test:
          - { name: "AES", pattern: AES }
          - { name: "SHA", pattern: SHA }
          - { name: "HMAC", pattern: HMAC }
          - { name: "Stack", pattern: Stack }
          - { name: "Karatsuba", pattern: Karatsuba }
          - { name: "Modulo", pattern: Modulo.Eq }
          - { name: "Inverse Modulo", pattern: InverseModulo }
          - { name: "CLU", pattern: CLU }
          - { name: "ECDSA", pattern: ECDSA }
          - { name: "ECDSA (Nonce)", pattern: Nonce.Deterministic }
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v5
      - name: "Repository specific setup"
        run: |
          deploykey "ghc-typelits-proof-assist" "${{ secrets.DEPLOY_KEY_PROOF_ASSIST_PLUGIN }}" && \
          echo "${{ env.NIX_CONFIG }}" >> /etc/nix/nix.conf && \
          echo "${{ env.NETRC_FILE }}" > /etc/nix/netrc
      - name: "Run Simulation"
        uses: "./.github/actions/simulate"
        with:
          testcase: ${{ matrix.test.pattern }}

  HITLT-Bitstreams:
    name: "Synth: ${{ matrix.test.name }}"
    runs-on: [self-hosted, compute]
    container:
      image: ghcr.io/qbaylogic/clash-formal-ci:20260326-687dd7d
      options: --memory=${{ matrix.test.memory }}
    needs: [ nix-build ]
    strategy:
      matrix:
        test:
          - { name: "AES128", testcase: AES128, memory: 11g }
          - { name: "AES192", testcase: AES192, memory: 11g }
          - { name: "AES256", testcase: AES256, memory: 11g }
          - { name: "SHA1", testcase: SHA1, memory: 11g  }
          - { name: "SHA224", testcase: SHA224, memory: 11g }
          - { name: "SHA256", testcase: SHA256, memory: 11g }
          - { name: "HMAC (SHA256)", testcase: HMACSHA256, memory: 11g }
          - { name: "Stack", testcase: Stack, memory: 11g }
          - { name: "Karatsuba", testcase: Karatsuba, memory: 11g }
          - { name: "Karatsuba (Modulo)", testcase: KaratsubaModulo, memory: 11g }
          - { name: "Modulo", testcase: Modulo, memory: 11g }
          - { name: "Inv. Mod. (BEA)", testcase: BEA, memory: 11g }
          - { name: "Inv. Mod. (FastGCD)", testcase: FastGCD, memory: 11g }
          - { name: "Inv. Mod. (FLT-CTMI)", testcase: FltCtmi, memory: 11g }
          - { name: "Inv. Mod. (SICT-MI)", testcase: SictMi, memory: 11g }
          - { name: "CLU", testcase: CLU, memory: 11g }
          - { name: "Calculator", testcase: Calculator, memory: 11g }
          - { name: "ECDSA (Nonce)", testcase: DeterministicNonce, memory: 30g }
          - { name: "ECDSA (Sign)", testcase: ECDSASign, memory: 30g }
          - { name: "ECDSA (Public Key Derivation)", testcase: ECDSADerivePublicKey, memory: 30g }
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
      - name: "Repository specific setup"
        run: |
          deploykey "ghc-typelits-proof-assist" "${{ secrets.DEPLOY_KEY_PROOF_ASSIST_PLUGIN }}" && \
          echo "${{ env.NIX_CONFIG }}" >> /etc/nix/nix.conf && \
          echo "${{ env.NETRC_FILE }}" > /etc/nix/netrc
      - name: "Login to the local cache"
        run: |
          attic login \
            --set-default "${{ env.PROJECT }}" \
            "${{ env.ATTIC_CACHE }}" \
            "${{ secrets.ATTIC_PUSH_JWT_TOKEN }}"
      - name: "Build HITLT Bitstreams"
        uses: "./.github/actions/hitlt-bitstream"
        with:
          cache: ${{ env.PROJECT }}
          testcase: ${{ matrix.test.testcase }}

  HITL-Tests:
    name: "HITL: ${{ matrix.test.name }}"
    runs-on: [self-hosted, hardware-access, orangecrab]
    container:
      image: ghcr.io/qbaylogic/clash-formal-ci:20260326-687dd7d
      options: >-
        --memory=${{ matrix.test.memory }}
        --device /dev/bus/usb
        --device /dev/ttyPmodUSB0
    needs: [ HITLT-Bitstreams ]
    strategy:
      matrix:
        test:
          - { name: "AES128", pattern: AES.AES128, memory: 11g }
          - { name: "AES192", pattern: AES.AES192, memory: 11g }
          - { name: "AES256", pattern: AES.AES256, memory: 11g }
          - { name: "SHA1", pattern: SHA.SHA1, memory: 11g }
          - { name: "SHA224", pattern: SHA.SHA224, memory: 11g }
          - { name: "SHA256", pattern: SHA.SHA256, memory: 11g }
          - { name: "HMAC (SHA256)", pattern: HMACSHA256, memory: 11g }
          - { name: "Stack", pattern: Stack, memory: 11g }
          - { name: "Karatsuba", pattern: Karatsuba, memory: 11g }
          - { name: "Modulo", pattern: Modulo.Modulo, memory: 11g }
          - { name: "Inv. Mod. (BEA)", pattern: BEA, memory: 11g }
          - { name: "Inv. Mod. (FastGCD)", pattern: FastGCD, memory: 11g }
          - { name: "Inv. Mod. (FLT-CTMI)", pattern: FltCtmi, memory: 11g }
          - { name: "CLU", pattern: CLU, memory: 11g }
          - { name: "Calculator", pattern: Calculator.Calculator, memory: 11g }
          - { name: "ECDSA (Sign)", pattern: ECDSA.Sign, memory: 30g }
          - { name: "ECDSA (Nonce)", pattern: Nonce.Deterministic, memory: 11g }
          - { name: "ECDSA (Public Key Derivation)", pattern: ECDSADerivePublicKey, memory: 30g }
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v5
      - name: "Repository specific setup"
        run: |
          deploykey "ghc-typelits-proof-assist" "${{ secrets.DEPLOY_KEY_PROOF_ASSIST_PLUGIN }}" && \
          echo "${{ env.NIX_CONFIG }}" >> /etc/nix/nix.conf && \
          echo "${{ env.NETRC_FILE }}" > /etc/nix/netrc
      - name: "Run HITLT"
        uses: "./.github/actions/hitlt"
        with:
          testcase: ${{ matrix.test.pattern }}

  all:
    name: All jobs finished
    if: ${{ !cancelled() }}
    needs: [ pre-check, Simulation-Tests, HITL-Tests ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check dependencies for failures
        run: |
          # Test all dependencies for success/failure
          set -x
          success="${{ contains(needs.*.result, 'success') }}"
          fail="${{ contains(needs.*.result, 'failure') }}"
          set +x

          # Test whether success/fail variables contain sane values
          if [[ "${success}" != "true" && "${success}" != "false" ]]; then exit 1; fi
          if [[ "${fail}"    != "true" && "${fail}"    != "false" ]]; then exit 1; fi

          # We want to fail if one or more dependencies fail. For safety, we introduce
          # a second check: if no dependencies succeeded something weird is going on.
          if [[ "${fail}" == "true" || "${success}" == "false" ]]; then
            echo "One or more dependency failed, or no dependency succeeded."
            exit 1
          fi
